version: '3.1'

services:
  mongostore:
    image: mongo:4.2-bionic
    ports:
        - 37017:27017
    volumes: 
      - /data/botmincock:/data/db
    healthcheck:
      # NOTE: other services can only start running when this service is up and running
      # NOTE: other services will run this test to know if this service is up
      test: "exit 0"
    tty: true
    stdin_open: true
    container_name: ctn_store
  botmincock:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - SRC=${SRCDIR}
        - LOG=${LOGDIR}
        - RUN=${RUNDIR}
        - ETC=${ETCDIR}
        - BIN=${BINDIR}
    ports:
      - 8080:8080
      - 3333:3333
    volumes:
      - ${LOGDIR}:${LOGDIR}
    links:
      - mongostore
    depends_on:
      mongostore:
        condition: service_healthy
    environment: 
      - LOGF=${LOGDIR}/botmincock.log
      - GIN_MODE=${GIN_MODE}
      - BOT_HANDLE=${BOT_HANDLE}
      - BOT_NAME=${BOT_NAME}
      - PSABADMIN_GRP=${PSABADMIN_GRP}
      - GUEST_CHARGE=${GUEST_CHARGE}
    stdin_open: true 
    tty: true
    container_name: ctn_botminc
    entrypoint: ["${BINDIR}/entry.sh", "-v=${VERBOSE}", "-f=${FLOG}", "-s=${SEED}"]
    secrets:
      - token_secret
secrets:
  token_secret:
    file: tok.secret